#!/bin/sh
prefix="$1"
shift


case "$prefix" in

  login | i)  # the agr is a webpage
    list_file=~/.local/share/al/type
    webpage="${1:-"$(cut -d ' ' -f 1 < "$list_file" | alc-talk recommend 'xdotool type')"}"
    test "$webpage" || exit
    find_entry() {
      grep -F "$webpage" "$list_file"
    }
    keys="$(find_entry | cut -d ' ' -f 2-)"
    xdotool type "$keys"
    ;;

  *)
    echo "invalid command: $prefix" >&2
    exit 1
    ;;

esac
