#!/bin/env sh

alm_snip_conf_dir="${AL_SNIPPETS:-"$HOME/.config/alsnip"}"
help() {
  cat <<EOM
Looks for config files in \$AL_SNIPPETS OR ~/.config/alsnip
(now it's $alm_snip_conf_dir)
and not only. It calls agents from the 2 agents directories,
which you should go find yourself and go fuck yourself
as well, I'm too tired to code properly.
EOM
}

ask_all() {
  for d in agents/*
  do "$d" "$@"
  done
}

on_first() {
  for d in agents/*
  do "$d" "$@" && return
  done
  return 1
}

main() {
  case "$1" in
    --help | -h) help ;;  # Print this help
    list) ask_all "$@" ;;  # [TAG] Get a list of script IDs
    preview) ask_all "$@" ;;  # [TAG] Preview all snippets with the tag
    unpreview) cut -d' ' -f1 ;;  # stdin preview, stdout original

    info) on_first "$@" ;;        # SCRIPT_NAME
    self-or-stdout) self_or_stdout "$2" "$3" ;;  # TAG SCRIPT_NAME  consider as-is or pipe to sh

    print) on_first "$@" ;;
    print-wrapped) on_first "$@" ;;  # SCRIPT_NAME TAG
    colored-wrapped) on_first "$@" ;;  # SCRIPT_NAME TAG
    chop-key-bindings) ask_all "$@" ;;  # for hooking hotkey systems (try it)
    aliases-as-posix) ask_all "$@" ;;

    print-duplicates) ask_all "$@" ;;  # outputs the duplicates to stdout
    there-are-duplicates) [ "$(ask_all print-duplicates)" ] || exit 1 ;;  # exits with 1 if there are duplicates
    lacking-newline) ask_all "$@" ;;  # prints scripts that lack newlines
    there-are-newline-lackers) [ "$(ask_all lacking-newline)" ] || exit 1 ;;  # silent, exits with 1

    *) echo 'Sorry invalid flag, try --help' >&2 ; exit 1 ;;
  esac
}

main "$@"
